let fooditem=[
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        description:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },

]


