let fooditem=[
    {
        nom :'chicken burgers',
        img :'img/chicen.jpeg',
        note:4.6,
        category:'american',
        genre:'chicken',
        ingredients:'poulet, tomate, oignon, salade, avocat',
        preparationtime:'10-15 min',
        prix:'10€',
    },
    {
        nom :'ultimate bacon king',
        img :'img/bacon king.jpeg',
        note:4.3,
        category:'american',
        genre:'meat',
        ingredients:'minced steak, lots of bacon, cheese, special sauce',
        preparationtime:'10-15 min',
        prix:'10€',
    },
    {
        nom :'tacos grecque',
        img :'img/tacos-a-la-grecque.jpg',
        note:4.4,
        category:'mexican',
        genre:'chicken',
        ingredients:'ground pork, salad, olive, onion, pita sauce',
        preparationtime:'10 min',
        prix:'8€',
    },
    {
        nom :'suprem tacos',
        img :'img/tacosmex.jpeg',
        note:4.5,
        category:'mexican',
        genre:'meat',
        ingredients:'chopped beef, tomato, avocado, pepper, lemon worms, onion',
        preparationtime:'15 min',
        prix:'12€',
    },
    {
        nom :'durum piment',
        img :'img/durump.jpeg',
        note:4.2,
        category:'turkey',
        genre:'meat',
        ingredients:'veal, turkey, cumin, chilli, tomatoes, onion, chives',
        preparationtime:'15 min',
        prix:'11€',
    },
    {
        nom :'durum chicken',
        img :'img/dour.jpeg',
        note:4.3,
        category:'turkey',
        genre:'chicken',
        ingredients:'chicken, onion, pepper, garlic, tomato, parsley',
        preparationtime:'10 min',
        prix:'11€',
    },
    {
        nom :'salade cesar',
        img :'img/slac.jpeg',
        note:4.1,
        category:'american',
        genre:'salad',
        ingredients:'lettuce, chicken, bread, cream, anchovies, parmesan, caper, garlic',
        preparationtime:'10 min',
        prix:'8€',
    },
    {
        nom :'salade quinoa',
        img :'img/quinoa.jpg',
        note:4.3,
        category:'american',
        genre:'salad',
        ingredients:'quinoa, bell pepper, red cabbage, carrots, peanut butter, ginger',
        preparationtime:'10 min',
        prix:'13€',

    },
    {
        nom :'nouilles poulet',
        img :'img/nouillesp.jpeg',
        note:4.2,
        category:'Chinese',
        genre:'chicken',
        ingredients:'chicken, broccoli, carrots, onion, garlic, soy sauce',
        preparationtime:'10-15 min',
        prix:'13€',
    },
    {
        nom :'nouilles beauf',
        img :'img/nouillesb.jpeg',
        note:4.8,
        category:'Chinese',
        genre:'meat',
        ingredients:'beef, beans, ginger, soy sauce, Chinese cabbage',
        preparationtime:'10-15 min',
        prix:'11€',
    },
    {
        nom :'plateau japan roll mixte',
        img :'img/rols1.png',
        note:4.2,
        category:'Chinese',
        genre:'meat',
        ingredients:'nori sheets, sesame, rice, wasabi, avocado, cucumber, crab, soy sauce',
        preparationtime:'15 min',
        prix:'20€',
    },
    {
        nom :'pizza 4 fromages',
        img :'img/pizza4.png',
        note:4.5,
        category:'italy',
        genre:'vegetarian',
        ingredients:'tomato, cheddar, county, blue cheese, mozzarella, basil',
        preparationtime:'20 min',
        prix:'15€',
    },
    {
        nom :'pizza calzone',
        img :'img/calzo.jpg',
        note:4.7,
        category:'italy',
        genre:'meat',
        ingredients:'tomato, gruyère, oregano, ham, shallot, mozzarella, olive',
        preparationtime:'20 min',
        prix:'15€',
    },
    {
        nom :'pâtes carbonara',
        img :'img/pattec.jpeg',
        note:4.8,
        category:'italy',
        genre:'meat',
        ingredients:'cream, onion, bacon, egg, cheese',
        preparationtime:'15 min',
        prix:'12€',
    },
    {
        nom :'pâtes bolognaise',
        img :'img/patteb.jpg',
        note:4.7,
        category:'italy',
        genre:'meat',
        ingredients:'tomato, onion, carrot, celery, parsley, ground beef',
        preparationtime:'15 min',
        prix:'14€',

    },
    {
        nom :'boulette frite',
        img :'img/boulet.jpg',
        note:3.9,
        category:'belgian',
        genre:'meat',
        ingredients:'minced beef, onion, parsley, eggs, cork syrup, tomato, fried',
        preparationtime:'15 min',
        prix:'15€',
    },
    {
        nom :'calamar à la romaine',
        img :'img/calamar.jpg',
        note:4.3,
        category:'spain',
        genre:'crustacean',
        ingredients:'squid, egg, lemon, onion,',
        preparationtime:'10 min',
        prix:'10€',
    },
    {
        nom :'plateau de fruit de mer',
        img :'img/plateau.jpg',
        note:4.6,
        category:'spain',
        genre:'crustacean',
        ingredients:'winkles, whelks, clams, oysters, cakes, crabs, shrimp',
        preparationtime:'25 min',
        prix:'40€',
    },
    {
        nom :'ramen chicken',
        img :'img/ramen.jpg',
        note:4.7,
        category:'chinese',
        genre:'chicken',
        ingredients:'chicken, with, sesame, onion, soy, chicken broth',
        preparationtime:'10-15min',
        prix:'12€',
    },
    {
        nom :'spicy ramen',
        img :'img/ramenp.jpg',
        note:4.5,
        category:'chinese',
        genre:'meat',
        ingredients:'beef, soy, onion, shiitake, miso, sesame, garlic, chilli, vegetable broth',
        preparationtime:'10-15 min',
        prix:'14€',
    },

]


