let fooditem=[
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },
    {
        nom :'',
        img :'',
        vegan:'',
        halal:'',
        note:'',
        category:"",
        ingredients:'',
        preparationtime:'',
        prix:'',
    },

]


